### ISSUE TITLE
`@ofborg test installer` did not run installer tests, yet succeeded

### ISSUE THREAD

**Issue by roberth** [NixOS/ofborg#608] opened 2022-06-25 08:20 UTC
See https://github.com/NixOS/nixpkgs/pull/177672#event-6867843030

**Comment by ncfavier** [comment] 2023-01-01 16:40
Duplicate of https://github.com/NixOS/ofborg/issues/504, the workaround is `@ofborg build nixosTests.installer`.

**Comment by cole-h** [comment] 2023-02-04 02:18
Since https://github.com/NixOS/ofborg/pull/630, we've switched to using `nixosTests` rather than the `nixos/release.nix`'s `tests` :)

**Closed as completed by cole-h** 2023-02-04 02:18 UTC
